# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Counting-ReSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'ReSwift'
  # Pods for Counting-ReSwift

end
